name: Make camp

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: compile
      run: |
        echo "build start"
        pwd
        ls -al 
        pwd
        ./build.sh
        ./bin/camp
        echo "build end"
    - name: Artifact
      uses: actions/upload-artifact@v2
      with:
        name: assets-for-download
        path: bin

